// AUTO-GENERATED by tools/scraper/build-catalog-assets.mjs — do not edit by hand.
// Categories/gallery: polure reference shots (TEMPORARY placeholders — replace before launch).
// Projects/hero: kartonpiyerdeposu.com (own) photos.

export const CATEGORY_IMAGES: Record<string, string[]> = {
  "sove": [
    "/catalog/sove/0.webp",
    "/catalog/sove/1.webp",
    "/catalog/sove/2.webp",
    "/catalog/sove/3.webp",
    "/catalog/sove/4.webp",
    "/catalog/sove/5.webp",
    "/catalog/sove/6.webp",
    "/catalog/sove/7.webp"
  ],
  "sutun-baslik": [
    "/catalog/sutun-baslik/0.webp",
    "/catalog/sutun-baslik/1.webp",
    "/catalog/sutun-baslik/2.webp",
    "/catalog/sutun-baslik/3.webp",
    "/catalog/sutun-baslik/4.webp",
    "/catalog/sutun-baslik/5.webp",
    "/catalog/sutun-baslik/6.webp",
    "/catalog/sutun-baslik/7.webp"
  ],
  "kemer": [
    "/catalog/kemer/0.webp",
    "/catalog/kemer/1.webp",
    "/catalog/kemer/2.webp",
    "/catalog/kemer/3.webp",
    "/catalog/kemer/4.webp",
    "/catalog/kemer/5.webp",
    "/catalog/kemer/6.webp",
    "/catalog/kemer/7.webp"
  ],
  "kartonpiyer": [
    "/catalog/kartonpiyer/0.webp",
    "/catalog/kartonpiyer/1.webp",
    "/catalog/kartonpiyer/2.webp",
    "/catalog/kartonpiyer/3.webp",
    "/catalog/kartonpiyer/4.webp",
    "/catalog/kartonpiyer/5.webp",
    "/catalog/kartonpiyer/6.webp",
    "/catalog/kartonpiyer/7.webp"
  ],
  "gobek": [
    "/catalog/gobek/0.webp",
    "/catalog/gobek/1.webp",
    "/catalog/gobek/2.webp",
    "/catalog/gobek/3.webp",
    "/catalog/gobek/4.webp",
    "/catalog/gobek/5.webp",
    "/catalog/gobek/6.webp",
    "/catalog/gobek/7.webp"
  ],
  "kubbe": [
    "/catalog/kubbe/0.webp",
    "/catalog/kubbe/1.webp",
    "/catalog/kubbe/2.webp",
    "/catalog/kubbe/3.webp",
    "/catalog/kubbe/4.webp",
    "/catalog/kubbe/5.webp",
    "/catalog/kubbe/6.webp",
    "/catalog/kubbe/7.webp"
  ],
  "tac": [
    "/catalog/tac/0.webp",
    "/catalog/tac/1.webp",
    "/catalog/tac/2.webp",
    "/catalog/tac/3.webp",
    "/catalog/tac/4.webp",
    "/catalog/tac/5.webp",
    "/catalog/tac/6.webp",
    "/catalog/tac/7.webp"
  ],
  "cita-lambri": [
    "/catalog/cita-lambri/0.webp",
    "/catalog/cita-lambri/1.webp",
    "/catalog/cita-lambri/2.webp",
    "/catalog/cita-lambri/3.webp",
    "/catalog/cita-lambri/4.webp",
    "/catalog/cita-lambri/5.webp",
    "/catalog/cita-lambri/6.webp",
    "/catalog/cita-lambri/7.webp"
  ],
  "panel-kaplama": [
    "/catalog/panel-kaplama/0.webp",
    "/catalog/panel-kaplama/1.webp",
    "/catalog/panel-kaplama/2.webp",
    "/catalog/panel-kaplama/3.webp",
    "/catalog/panel-kaplama/4.webp",
    "/catalog/panel-kaplama/5.webp",
    "/catalog/panel-kaplama/6.webp",
    "/catalog/panel-kaplama/7.webp"
  ],
  "payanda": [
    "/catalog/payanda/0.webp",
    "/catalog/payanda/1.webp",
    "/catalog/payanda/2.webp",
    "/catalog/payanda/3.webp",
    "/catalog/payanda/4.webp",
    "/catalog/payanda/5.webp",
    "/catalog/payanda/6.webp",
    "/catalog/payanda/7.webp"
  ],
  "kiris": [
    "/catalog/kiris/0.webp",
    "/catalog/kiris/1.webp",
    "/catalog/kiris/2.webp",
    "/catalog/kiris/3.webp",
    "/catalog/kiris/4.webp",
    "/catalog/kiris/5.webp",
    "/catalog/kiris/6.webp",
    "/catalog/kiris/7.webp"
  ],
  "susleme": [
    "/catalog/susleme/0.webp",
    "/catalog/susleme/1.webp",
    "/catalog/susleme/2.webp",
    "/catalog/susleme/3.webp",
    "/catalog/susleme/4.webp",
    "/catalog/susleme/5.webp",
    "/catalog/susleme/6.webp",
    "/catalog/susleme/7.webp"
  ],
  "supurgelik": [
    "/catalog/supurgelik/0.webp",
    "/catalog/supurgelik/1.webp",
    "/catalog/supurgelik/2.webp",
    "/catalog/supurgelik/3.webp",
    "/catalog/supurgelik/4.webp",
    "/catalog/supurgelik/5.webp"
  ],
  "somine": [
    "/catalog/somine/0.webp",
    "/catalog/somine/1.webp",
    "/catalog/somine/2.webp",
    "/catalog/somine/3.webp",
    "/catalog/somine/4.webp"
  ],
  "kupeste-balustr": [
    "/catalog/kupeste-balustr/0.webp",
    "/catalog/kupeste-balustr/1.webp",
    "/catalog/kupeste-balustr/2.webp",
    "/catalog/kupeste-balustr/3.webp",
    "/catalog/kupeste-balustr/4.webp",
    "/catalog/kupeste-balustr/5.webp",
    "/catalog/kupeste-balustr/6.webp",
    "/catalog/kupeste-balustr/7.webp"
  ],
  "yapistirici-aksesuar": [
    "/catalog/yapistirici-aksesuar/0.webp",
    "/catalog/yapistirici-aksesuar/1.webp"
  ]
};

export const PROJECT_IMAGES: string[] = [
  "/projects/0.webp",
  "/projects/1.webp",
  "/projects/2.webp",
  "/projects/3.webp",
  "/projects/4.webp",
  "/projects/5.webp",
  "/projects/6.webp",
  "/projects/7.webp",
  "/projects/8.webp"
];

export const GALLERY_IMAGES: string[] = [
  "/catalog/sove/0.webp",
  "/catalog/sove/1.webp",
  "/catalog/sove/2.webp",
  "/catalog/sove/3.webp",
  "/catalog/sutun-baslik/0.webp",
  "/catalog/sutun-baslik/1.webp",
  "/catalog/sutun-baslik/2.webp",
  "/catalog/sutun-baslik/3.webp",
  "/catalog/kemer/0.webp",
  "/catalog/kemer/1.webp",
  "/catalog/kemer/2.webp",
  "/catalog/kemer/3.webp",
  "/catalog/kartonpiyer/0.webp",
  "/catalog/kartonpiyer/1.webp",
  "/catalog/kartonpiyer/2.webp",
  "/catalog/kartonpiyer/3.webp",
  "/catalog/gobek/0.webp",
  "/catalog/gobek/1.webp",
  "/catalog/gobek/2.webp",
  "/catalog/gobek/3.webp",
  "/catalog/kubbe/0.webp",
  "/catalog/kubbe/1.webp",
  "/catalog/kubbe/2.webp",
  "/catalog/kubbe/3.webp",
  "/catalog/tac/0.webp",
  "/catalog/tac/1.webp",
  "/catalog/tac/2.webp",
  "/catalog/tac/3.webp",
  "/catalog/cita-lambri/0.webp",
  "/catalog/cita-lambri/1.webp",
  "/catalog/cita-lambri/2.webp",
  "/catalog/cita-lambri/3.webp",
  "/catalog/panel-kaplama/0.webp",
  "/catalog/panel-kaplama/1.webp",
  "/catalog/panel-kaplama/2.webp",
  "/catalog/panel-kaplama/3.webp",
  "/catalog/payanda/0.webp",
  "/catalog/payanda/1.webp",
  "/catalog/payanda/2.webp",
  "/catalog/payanda/3.webp",
  "/catalog/kiris/0.webp",
  "/catalog/kiris/1.webp",
  "/catalog/kiris/2.webp",
  "/catalog/kiris/3.webp"
];

export const HERO_IMAGES: string[] = [
  "/hero/0.webp",
  "/hero/1.webp",
  "/hero/2.webp",
  "/hero/3.webp",
  "/hero/4.webp",
  "/hero/5.webp"
];

/** First image for a category, if any. */
export function categoryImage(slug: string): string | null {
  return CATEGORY_IMAGES[slug]?.[0] ?? null;
}
