// AUTO-GENERATED by Supabase (mcp generate_typescript_types). Regenerate after schema changes.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      categories: {
        Row: {
          created_at: string
          description: string | null
          id: string
          image_path: string | null
          is_active: boolean
          name_en: string | null
          name_tr: string
          parent_id: string | null
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          image_path?: string | null
          is_active?: boolean
          name_en?: string | null
          name_tr: string
          parent_id?: string | null
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          image_path?: string | null
          is_active?: boolean
          name_en?: string | null
          name_tr?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          company: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          kind: string
          message: string | null
          phone: string | null
          product_codes: string[] | null
          role: string | null
          source: string | null
          status: string
          updated_at: string
        }
        Insert: {
          company?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          kind?: string
          message?: string | null
          phone?: string | null
          product_codes?: string[] | null
          role?: string | null
          source?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          company?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          kind?: string
          message?: string | null
          phone?: string | null
          product_codes?: string[] | null
          role?: string | null
          source?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      product_images: {
        Row: {
          alt: string | null
          created_at: string
          id: string
          is_primary: boolean
          product_id: string
          sort_order: number
          url: string
        }
        Insert: {
          alt?: string | null
          created_at?: string
          id?: string
          is_primary?: boolean
          product_id: string
          sort_order?: number
          url: string
        }
        Update: {
          alt?: string | null
          created_at?: string
          id?: string
          is_primary?: boolean
          product_id?: string
          sort_order?: number
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          category_id: string | null
          code: string
          created_at: string
          currency: string
          description_en: string | null
          description_tr: string | null
          diameter_mm: number | null
          drawing_url: string | null
          height_mm: number | null
          id: string
          indoor: boolean | null
          is_active: boolean
          is_featured: boolean
          length_mm: number | null
          material: string | null
          min_level: number
          name_en: string | null
          name_tr: string
          outdoor: boolean | null
          paintable: boolean | null
          price: number | null
          seo_description: string | null
          seo_title: string | null
          slug: string | null
          sort_order: number
          stock_qty: number
          track_stock: boolean
          unit: string
          updated_at: string
          water_resistant: boolean | null
          weight_g: number | null
          width_mm: number | null
        }
        Insert: {
          category_id?: string | null
          code: string
          created_at?: string
          currency?: string
          description_en?: string | null
          description_tr?: string | null
          diameter_mm?: number | null
          drawing_url?: string | null
          height_mm?: number | null
          id?: string
          indoor?: boolean | null
          is_active?: boolean
          is_featured?: boolean
          length_mm?: number | null
          material?: string | null
          min_level?: number
          name_en?: string | null
          name_tr: string
          outdoor?: boolean | null
          paintable?: boolean | null
          price?: number | null
          seo_description?: string | null
          seo_title?: string | null
          slug?: string | null
          sort_order?: number
          stock_qty?: number
          track_stock?: boolean
          unit?: string
          updated_at?: string
          water_resistant?: boolean | null
          weight_g?: number | null
          width_mm?: number | null
        }
        Update: {
          category_id?: string | null
          code?: string
          created_at?: string
          currency?: string
          description_en?: string | null
          description_tr?: string | null
          diameter_mm?: number | null
          drawing_url?: string | null
          height_mm?: number | null
          id?: string
          indoor?: boolean | null
          is_active?: boolean
          is_featured?: boolean
          length_mm?: number | null
          material?: string | null
          min_level?: number
          name_en?: string | null
          name_tr?: string
          outdoor?: boolean | null
          paintable?: boolean | null
          price?: number | null
          seo_description?: string | null
          seo_title?: string | null
          slug?: string | null
          sort_order?: number
          stock_qty?: number
          track_stock?: boolean
          unit?: string
          updated_at?: string
          water_resistant?: boolean | null
          weight_g?: number | null
          width_mm?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      project_images: {
        Row: {
          alt: string | null
          id: string
          project_id: string
          sort_order: number
          url: string
        }
        Insert: {
          alt?: string | null
          id?: string
          project_id: string
          sort_order?: number
          url: string
        }
        Update: {
          alt?: string | null
          id?: string
          project_id?: string
          sort_order?: number
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_images_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_products: {
        Row: {
          product_id: string
          project_id: string
        }
        Insert: {
          product_id: string
          project_id: string
        }
        Update: {
          product_id?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_products_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          cover_url: string | null
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          location: string | null
          seo_description: string | null
          seo_title: string | null
          slug: string
          sort_order: number
          summary: string | null
          title: string
          updated_at: string
          year: number | null
        }
        Insert: {
          cover_url?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          location?: string | null
          seo_description?: string | null
          seo_title?: string | null
          slug: string
          sort_order?: number
          summary?: string | null
          title: string
          updated_at?: string
          year?: number | null
        }
        Update: {
          cover_url?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          location?: string | null
          seo_description?: string | null
          seo_title?: string | null
          slug?: string
          sort_order?: number
          summary?: string | null
          title?: string
          updated_at?: string
          year?: number | null
        }
        Relationships: []
      }
      service_products: {
        Row: {
          product_id: string
          service_id: string
        }
        Insert: {
          product_id: string
          service_id: string
        }
        Update: {
          product_id?: string
          service_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_products_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      services: {
        Row: {
          content: string | null
          created_at: string
          cta_label: string | null
          description: string | null
          icon: string | null
          id: string
          image_url: string | null
          is_active: boolean
          seo_description: string | null
          seo_title: string | null
          slug: string
          sort_order: number
          summary: string | null
          title: string
          updated_at: string
        }
        Insert: {
          content?: string | null
          created_at?: string
          cta_label?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          seo_description?: string | null
          seo_title?: string | null
          slug: string
          sort_order?: number
          summary?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          content?: string | null
          created_at?: string
          cta_label?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          seo_description?: string | null
          seo_title?: string | null
          slug?: string
          sort_order?: number
          summary?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      stock_movements: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          note: string | null
          product_id: string
          quantity: number
          reason: string | null
          ref: string | null
          type: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          note?: string | null
          product_id: string
          quantity: number
          reason?: string | null
          ref?: string | null
          type: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          note?: string | null
          product_id?: string
          quantity?: number
          reason?: string | null
          ref?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_movements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      apply_stock_movement: {
        Args: {
          p_note?: string
          p_product: string
          p_qty: number
          p_reason?: string
          p_ref?: string
          p_type: string
        }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicTables = Database["public"]["Tables"]
export type Category = PublicTables["categories"]["Row"]
export type Product = PublicTables["products"]["Row"]
export type ProductImage = PublicTables["product_images"]["Row"]
export type Lead = PublicTables["leads"]["Row"]
export type ProductInsert = PublicTables["products"]["Insert"]
export type CategoryInsert = PublicTables["categories"]["Insert"]
export type StockMovement = PublicTables["stock_movements"]["Row"]
